
apiVersion: v1
kind: Secret
metadata:
  name: drycc-storage-creds
  labels:
    heritage: drycc
type: Opaque
data:
  {{- if and (eq .Values.global.certManagerEnabled "false") ( eq .Values.tls.enabled "true" ) }}
  {{- $altNames := list ( printf "*.%s.%s" .Release.Namespace .Values.global.clusterDomain ) ( printf "*.%s.svc.%s" .Release.Namespace .Values.global.clusterDomain ) -}}
  {{- $ca := genCA "drycc-storage-ca" 3650 -}}
  {{- $cert := genSignedCert "drycc-storage-ca" nil $altNames 3650 $ca }}
  ca.crt: {{ $ca.Cert | b64enc }}
  tls.crt: {{ $cert.Cert | b64enc }}
  tls.key: {{ $cert.Key | b64enc }}
  {{- end }}
  accesskey: {{ if .Values.accesskey | default "" | ne "" }}{{ .Values.accesskey | b64enc }}{{ else }}{{ randAlphaNum 32 | b64enc }}{{ end }}
  secretkey: {{ if .Values.secretkey | default "" | ne "" }}{{ .Values.secretkey | b64enc }}{{ else }}{{ randAlphaNum 32 | b64enc }}{{ end }}
  jwtkey: {{ if .Values.jwtkey | default "" | ne "" }}{{ .Values.jwtkey | b64enc }}{{ else }}{{ randAlphaNum 32 | b64enc }}{{ end }}
