apiVersion: v1
kind: Secret
metadata:
  name: drycc-storage-creds
  labels:
    heritage: drycc
type: Opaque
data:
  {{- $altNames := list
    ( printf "*.%s.%s.svc.%s" "drycc-storage-mainnode" .Release.Namespace .Values.global.clusterDomain )
    ( printf "*.%s.%s.svc.%s" "drycc-storage-metanode" .Release.Namespace .Values.global.clusterDomain )
    ( printf "*.%s.%s.svc.%s" "drycc-storage-datanode" .Release.Namespace .Values.global.clusterDomain )
    ( printf "*.%s.svc.%s" .Release.Namespace .Values.global.clusterDomain )
  -}}
  {{- $ca := genCA "drycc-storage-ca" 3650 -}}
  {{- $cert := genSignedCert "drycc-storage-cert" nil $altNames 3650 $ca }}
  ca.crt: {{ $ca.Cert | b64enc }}
  tls.crt: {{ $cert.Cert | b64enc }}
  tls.key: {{ $cert.Key | b64enc }}
  accesskey: {{ if .Values.accesskey | default "" | ne "" }}{{ .Values.accesskey | b64enc }}{{ else }}{{ randAlphaNum 32 | b64enc }}{{ end }}
  secretkey: {{ if .Values.secretkey | default "" | ne "" }}{{ .Values.secretkey | b64enc }}{{ else }}{{ randAlphaNum 32 | b64enc }}{{ end }}
  jwtkey: {{ if .Values.jwtkey | default "" | ne "" }}{{ .Values.jwtkey | b64enc }}{{ else }}{{ randAlphaNum 32 | b64enc }}{{ end }}
