{{- if eq .Values.global.storageLocation "on-cluster" }}
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: drycc-storage
  annotations:
provisioner: seaweedfs-csi-driver
allowVolumeExpansion: true
{{- end }}
