kind: StatefulSet
apiVersion: apps/v1
metadata:
  name: drycc-storage-csi-controller
spec:
  selector:
    matchLabels:
      app: drycc-storage-csi-controller
  serviceName: drycc-storage-csi-controller
  replicas: 1
  template:
    metadata:
      labels:
        app: drycc-storage-csi-controller
    spec:
      priorityClassName: system-cluster-critical
      serviceAccountName: drycc-storage-csi
      containers:
        - name: drycc-storage-csi-controller-provisioner
          image: {{ .Values.statefulset.provisionerImage }}
          args:
            - "--csi-address=$(ADDRESS)"
            - -v
            - "9"
          env:
            - name: ADDRESS
              value: /var/lib/csi/sockets/pluginproxy/csi.sock
          imagePullPolicy: IfNotPresent
          volumeMounts:
            - name: socket-dir
              mountPath: /var/lib/csi/sockets/pluginproxy/
        - name: drycc-storage-csi-controller-attacher
          image: {{ .Values.statefulset.attacherImage }}
          args:
            - "--v=5"
            - "--csi-address=$(ADDRESS)"
            - "--timeout=120s"
          env:
            - name: ADDRESS
              value: /var/lib/csi/sockets/pluginproxy/csi.sock
          imagePullPolicy: IfNotPresent
          volumeMounts:
            - name: socket-dir
              mountPath: /var/lib/csi/sockets/pluginproxy/
        # resizer
        - name: drycc-storage-csi-controller-resizer
          image: {{ .Values.statefulset.resizerImage }}
          args:
            - "--v=5"
            - "--csi-address=$(ADDRESS)"
            - "--leader-election=false"
          env:
            - name: ADDRESS
              value: /var/lib/csi/sockets/pluginproxy/csi.sock
          imagePullPolicy: IfNotPresent
          volumeMounts:
            - name: socket-dir
              mountPath: /var/lib/csi/sockets/pluginproxy/
        - name: drycc-storage-csi-controller-plugin
          image: {{ .Values.imageRegistry }}/{{ .Values.imageOrg }}/storage:{{ .Values.imageTag }}
          imagePullPolicy: IfNotPresent
          args:
            - "controls csi"
            - "--endpoint=$(CSI_ENDPOINT)"
            - "--filer=$(SEAWEEDFS_FILER)"
            - "--nodeid=$(NODE_ID)"
          env:
            - name: CSI_ENDPOINT
              value: unix:///var/lib/csi/sockets/pluginproxy/csi.sock
            - name: SEAWEEDFS_FILER
              value: "SEAWEEDFS_FILER:8888"
            - name: NODE_ID
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
          volumeMounts:
            - name: socket-dir
              mountPath: /var/lib/csi/sockets/pluginproxy/
      volumes:
        - name: socket-dir
          emptyDir: {}