{{- if eq .Values.global.storageLocation "on-cluster" }}
{{- $clusterDomain := .Value.global.clusterDomain }}
kind: DaemonSet
apiVersion: apps/v1
metadata:
  name: drycc-storage-csi-node
spec:
  selector:
    matchLabels:
      app: drycc-storage-csi-node
  updateStrategy:
    rollingUpdate:
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: drycc-storage-csi-node
    spec:
      priorityClassName: system-node-critical
      serviceAccountName: drycc-storage-csi
      containers:
        - name:  drycc-storage-csi-node-registrar
          image:  {{ .Values.daemonset.registrarImage }}
          imagePullPolicy: IfNotPresent
          args:
            - "--v=5"
            - "--csi-address=/csi/csi.sock"
            - "--kubelet-registration-path=/var/lib/kubelet/plugins/seaweedfs-csi-driver/csi.sock"
          env:
            - name: KUBE_NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
          volumeMounts:
            - name: plugin-dir
              mountPath: /csi/
            - name: registration-dir
              mountPath: /registration/
        - name: drycc-storage-csi-node-plugin
          securityContext:
            privileged: true
            capabilities:
              add: ["SYS_ADMIN"]
            allowPrivilegeEscalation: true
          image: {{ .Values.imageRegistry }}/{{ .Values.imageOrg }}/storage:{{ .Values.imageTag }}
          imagePullPolicy: IfNotPresent
          args :
            - "controls csi"
            - "--endpoint=unix:///csi/csi.sock"
            - "--filer=drycc-storage-metanode.${NAMESPACE}.svc.{{ $clusterDomain }}:18888"
            - "--nodeid=$(NODE_NAME)"
          env:
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          volumeMounts:
            - name: plugin-dir
              mountPath: /csi
            - name: pods-mount-dir
              mountPath: /var/lib/kubelet/pods
              mountPropagation: "Bidirectional"
            - mountPath: /dev
              name: device-dir
      volumes:
        - name: registration-dir
          hostPath:
            path: /var/lib/kubelet/plugins_registry/
            type: DirectoryOrCreate
        - name: plugin-dir
          hostPath:
            path: /var/lib/kubelet/plugins/seaweedfs-csi-driver
            type: DirectoryOrCreate
        - name: pods-mount-dir
          hostPath:
            path: /var/lib/kubelet/pods
            type: Directory
        - name: device-dir
          hostPath:
            path: /dev
{{- end }}
