{{- if eq .Values.global.storageLocation "on-cluster" }}
{{- $clusterDomain := .Values.global.clusterDomain }}
kind: StatefulSet
apiVersion: apps/v1
metadata:
  name: drycc-storage-csi-controller
spec:
  selector:
    matchLabels:
      app: drycc-storage-csi-controller
  serviceName: drycc-storage-csi-controller
  replicas: {{ .Values.csi.statefulset.replicas }}
  template:
    metadata:
      labels:
        app: drycc-storage-csi-controller
    spec:
      priorityClassName: system-cluster-critical
      serviceAccountName: drycc-storage-csi
      containers:
        - name: drycc-storage-csi-controller-provisioner
          image: {{ .Values.csi.statefulset.provisionerImage }}
          args:
            - "--csi-address=/var/lib/csi/sockets/pluginproxy/csi.sock"
            - -v
            - "9"
          imagePullPolicy: IfNotPresent
          volumeMounts:
            - name: socket-dir
              mountPath: /var/lib/csi/sockets/pluginproxy/
        - name: drycc-storage-csi-controller-attacher
          image: {{ .Values.csi.statefulset.attacherImage }}
          args:
            - "--v=5"
            - "--csi-address=/var/lib/csi/sockets/pluginproxy/csi.sock"
            - "--timeout=120s"
          imagePullPolicy: IfNotPresent
          volumeMounts:
            - name: socket-dir
              mountPath: /var/lib/csi/sockets/pluginproxy/
        # resizer
        - name: drycc-storage-csi-controller-resizer
          image: {{ .Values.csi.statefulset.resizerImage }}
          args:
            - "--v=5"
            - "--csi-address=/var/lib/csi/sockets/pluginproxy/csi.sock"
            - "--leader-election=false"
          imagePullPolicy: IfNotPresent
          volumeMounts:
            - name: socket-dir
              mountPath: /var/lib/csi/sockets/pluginproxy/
        - name: drycc-storage-csi-controller-plugin
          image: {{ .Values.imageRegistry }}/{{ .Values.imageOrg }}/storage:{{ .Values.imageTag }}
          imagePullPolicy: IfNotPresent
          args:
            - controls
            - csi
            - "--endpoint=unix:///var/lib/csi/sockets/pluginproxy/csi.sock"
            - "--filer=drycc-storage-metanode.${NAMESPACE}.svc.{{ $clusterDomain }}:18888"
            - "--nodeid=$(NODE_NAME)"
          env:
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          volumeMounts:
            - name: socket-dir
              mountPath: /var/lib/csi/sockets/pluginproxy/
      volumes:
        - name: socket-dir
          emptyDir: {}
{{- end }}
